### ISSUE TITLE
Issue with the naming in the master

### ISSUE THREAD

**Issue by agaget** [epics-modules/mrfioc2#120]
I am trying to resolve conflict for my Pull Request (https://github.com/epics-modules/mrfioc2/pull/119), I saw (what I think is) issue in the new naming recent naming added in the recent master branch. 
It's the branch master so maybe you are still working on it and I just have to wait, but if my remarks can help.

The fact that you add som `$(s=:)`in db (for example  `evrin.db`) I had to add `global {s="\$(s=:)"}` in `evr-mtca-300u.substitutions` otherwise 
```
record(mbbo, "$(IN)Trig$(s=:)Ext-Sel")
```
was resolved with `:` before I had the chance to change it from the startup.
```
record(longout, "$(P)$(dsh=-)In$(s=:)0$(ES)Code:Ext-SP") {
```` 
with the global `global {s="\$(s=:)"}`

```
record(longout, "$(P)$(dsh=-)In$(s=:)0$(ES)Code$(s=:)Ext-SP") {
````

**Comment by jerzyjamroz** [comment]
@agaget , this universal solution was developed by @zioven . I think you need to add ```global {s="\$(s=:)"}``` once you download the repo.

P.S.
I also added ```evr-mtca-300u.uv.substitutions``` so it can be used straight away.
