### ISSUE TITLE
Two file names as a file and an entry in Makefile are mismatched in evrMrmApp/src

### ISSUE THREAD

**Issue by jeonghanlee** [epics-modules/mrfioc2#15]
Hi Michael,

 In the evrMrmApp/src directory, Makefile refersthe following sources:
* drvemIocsh.c
* devemSetup.c

And, each filename has .cpp suffix.  However, the EPICS make system clever enough to figure out, so compilation has no issue at all. 

Two sources files are similar with c file instead of cpp, (please correct me if I am wrong) from my naive point of view.  What do you think?

**Comment by mdavidsaver** [comment]
Thanks for pointing this out.  Through a quirk of make rules this doesn't cause a technical problem, but can cause confusion.  Fixed with 73ca6447442603947f9b6d84df676a5388c74345
