### ISSUE TITLE
Out of date documentation

### ISSUE THREAD

**Issue by krmpotic** [epics-modules/mrfioc2#29]
evr-usage.lyx, chapter 9.10 Database Events is out of date with evrApp/Db/evrevent.db

**Comment by mdavidsaver** [comment]
Does anyone find the `EVR Device Support Reference` section a useful reference?  I'm inclined to remove it and shift the useful information someplace closer to the implementation.

**Comment by mdavidsaver** [comment]
I think I'll move the device support documentation into the .db files as comments.

**Comment by krmpotic** [comment]
I notice flashread, flashwrite usage only in evr-usage.lyx document. There is no mention of using this for upgrading EVM firmware.

Is it possible to flash EVM with these commands? If so, I think we should mention it in the documentation.

**Comment by jerzyjamroz** [comment]
The documentation update is ongoing in: https://github.com/epics-modules/mrfioc2/issues/79
