### ISSUE TITLE
topology id doesn't show EVR connected to port 8

### ISSUE THREAD

**Issue by krmpotic** [epics-modules/mrfioc2#49]
If EVR is disconnected and reconnected to another EVM port, topology id changes (PV "*ID-I").
If however EVR is disconnected and reconnected (accidentaly) to EVM's upstream port 8, topology id remains what it was. Link shows OK.

**Comment by mdavidsaver** [comment]
The ID record is 32-bit, and has ([ultimately](https://github.com/epics-modules/mrfioc2/blob/1a0112b3caa05f7e3e4bfc7c3a30ef356ff3cfc9/evrMrmApp/Db/mrmevrdc.template#L50)) a periodic scan.  I haven't spent much time playing around with DC features other than the central delay measurement.  Off hand I can't think of a reason why a register change wouldn't be reflected in the record.  Maybe the register itself isn't changing?  This could be checked with eg. `pciread` from the IOC shell.
