### ISSUE TITLE
Minor: Fix error message

### ISSUE THREAD

**Issue by anjohnson** [epics-modules/mrfioc2#64]
https://github.com/epics-modules/mrfioc2/blob/a8cb48d549b7aae13206cf2d168c6f1cfec2e1c4/evrApp/src/asub.c#L277

Given the line before it, the above should say `(UCHAR)` not `(DOUBLE)`.

**Comment by jerzyjamroz** [comment]
I did a look over errlogPrintf messages as your comment indicates basically more similar issues and I found a few just within asub.c file. It is merged now.
