### ISSUE TITLE
To align handling of the GTX outputs and #63 PR.

### ISSUE THREAD

**Issue by jerzyjamroz** [epics-modules/mrfioc2#96]
* https://github.com/epics-modules/mrfioc2/pull/87
* https://github.com/epics-modules/mrfioc2/pull/95
* https://github.com/epics-modules/mrfioc2/pull/94
VS
* https://github.com/epics-modules/mrfioc2/pull/63

**Comment by zioven** [comment]
missing reference to commit: 64b576325f4c8771b07360b42ee5d721a6a326ac
This commit provides the information so the driver maps the Inputs 16 and 17 as TCLKA and TCLKB (from MRF MTCA manual)
![image](https://github.com/epics-modules/mrfioc2/assets/31354133/1600f9a3-4a01-42b9-acc7-74c3dcde2388)

**Comment by jerzyjamroz** [comment]
@zioven , I did extensive CLKA tests today and I think my impelemtation is the way to go. It works as expected.

In summary:
* I will wait for you comment, once ok, I will merge this issue PRs (my part).
* Then, let's aggree the names for the EVR models within "mrmEvrSetupPCI" command.
* Then let's merge your code.

If anything, all ideas are welcome.

**Comment by zioven** [comment]
@jerzyjamroz Can you elaborate on the tests performed and what shortcomings had the second solution?

I am just curious and would like to understand if and how the performance is affected by both solutions.

**Comment by jerzyjamroz** [comment]
@zioven , the patches included here were used to run the CLKA output with 40-bit granularity (1 to 40-bit test was done successfully). The performance was on the level of ps. If you want more info, let's have a chat.

**Comment by jerzyjamroz** [comment]
@zioven , I will merge PR #94 and #95 at the end of the day. If you are too busy then I will merge the @ZanMaticPratnemer code with those PRs included in it.
